[package]
name = "jonmo"
version = "0.1.2"
edition = "2024"
categories = ["asynchronous", "gui", "game-development"]
description = "Bevy-native functional reactive signals"
exclude = ["assets/", ".github/", "crates/"]
keywords = ["reactive", "signals", "gamedev", "bevy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/databasedav/jonmo"
documentation = "https://docs.rs/jonmo"

[dependencies]
<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
bevy_ecs = "0.15.3"
bevy_reflect = "0.15.3"
bevy_log = "0.15.3"
bevy_app = "0.15.3"
<<<<<<< Updated upstream

[dev-dependencies]
bevy = "0.15.3"
=======
rand = "0.8" # Add rand dependency

[dev-dependencies]
bevy = "0.15.3"
>>>>>>> Stashed changes
>>>>>>> Stashed changes
