[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/bin/mold",
    "-Zshare-generics=y",
    "-C", "target-feature=+x87",
]

[unstable]
codegen-backend = true

[target.'cfg(not(target_arch = "wasm32"))'.profile.dev]
codegen-backend = "cranelift"

[target.'cfg(not(target_arch = "wasm32"))'.profile.dev.package."*"]
codegen-backend = "llvm"
